[Unit]
# The tnaudit service manages a python script that handles conversion of auditd
# messages to syslog-ng audit message for insertion into the X-NAS system
# audit database. The aforementioned python script is located in the scripts
# directory in the xnas_audit_rules repository. The tnaudit service
# should always be running while the auditd service is running.
Upholds=tnaudit.service
