"""Rename built-in unix groups truenas_* to xnas_*.

Renames four built-in groups in place so the product rebrand is complete:
- truenas_readonly_administrators (GID 951) -> xnas_readonly_administrators
- truenas_sharing_administrators  (GID 952) -> xnas_sharing_administrators
- truenas_webshare                (GID 445) -> xnas_webshare
- truenas_container_unpriv_root (user, UID 2147000001) -> xnas_container_unpriv_root

GIDs/UIDs are preserved so file ownership on existing datasets does not
need to be rewritten. /etc/group and /etc/passwd are regenerated by
middleware on next etc.generate cycle so the renames propagate.

Revision ID: d3e4f5a6b7c8
Revises: c2d3e4f5a6b7
Create Date: 2026-04-20 00:10:00.000000+00:00

"""
from alembic import op
from sqlalchemy.sql import text


revision = 'd3e4f5a6b7c8'
down_revision = 'c2d3e4f5a6b7'
branch_labels = None
depends_on = None


GROUP_RENAMES = [
    ('truenas_readonly_administrators', 'xnas_readonly_administrators'),
    ('truenas_sharing_administrators', 'xnas_sharing_administrators'),
    ('truenas_webshare', 'xnas_webshare'),
]
USER_RENAMES = [
    ('truenas_container_unpriv_root', 'xnas_container_unpriv_root'),
]


def upgrade():
    conn = op.get_bind()
    for old, new in GROUP_RENAMES:
        conn.execute(
            text("UPDATE account_bsdgroups SET bsdgrp_group = :new WHERE bsdgrp_group = :old"),
            {'new': new, 'old': old},
        )
    for old, new in USER_RENAMES:
        conn.execute(
            text("UPDATE account_bsdusers SET bsdusr_username = :new WHERE bsdusr_username = :old"),
            {'new': new, 'old': old},
        )


def downgrade():
    conn = op.get_bind()
    for old, new in GROUP_RENAMES:
        conn.execute(
            text("UPDATE account_bsdgroups SET bsdgrp_group = :old WHERE bsdgrp_group = :new"),
            {'new': new, 'old': old},
        )
    for old, new in USER_RENAMES:
        conn.execute(
            text("UPDATE account_bsdusers SET bsdusr_username = :old WHERE bsdusr_username = :new"),
            {'new': new, 'old': old},
        )
